import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by Emanuel Forlin",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
  <html>
    <body>
      <SessionProvider>
        <SidebarProvider>
          <AppSidebar>
            <main>
              <SidebarTrigger />
                {children}
            </main>
          </AppSidebar>
        </SidebarProvider>
      </SessionProvider>
    </body>
  </html>
  )
}
